### PR TITLE
Add Laravel 11 support

### PR DESCRIPTION
**Pull request by SamuelWillis**
Add Laravel 11 support

### CODE REVIEW

**Comment by SamuelWillis** [comment]
I have noticed that our SSO is broken currently so that will need fixing. Need to determine if it's something with Laravel 11 or not.

**Comment by SamuelWillis** [comment]
@brandonb927 @shaun-mac This is ready to go and has been tested on my laravel 11 branch.


https://github.com/echosec/phoenix/pull/13372

**Comment by brandonb927** [comment]
_sigh_ I REALLY wish we could replace this library but alas, we cannot.

**Review by brandonb927 — APPROVED** [review]

**Review by shaun-mac — APPROVED** [review]

**Comment by SamuelWillis** [comment]
@brandonb927 we could but it'd be a little lift and we'd have to write our own stuff.

Alternatively, we could rewrite our token system to use Ignite ones all the time and then not even need this... but yeah not happening any time soon i'd think.

**Pull request merged**
